/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivateRouteRouteImport } from './routes/_private/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrivateAdminRouteRouteImport } from './routes/_private/_admin/route'
import { Route as publicTestRouteRouteImport } from './routes/(public)/test/route'
import { Route as ApiTqTodosIndexRouteImport } from './routes/api/tq-todos/index'
import { Route as PrivateUserIndexRouteImport } from './routes/_private/user/index'
import { Route as PrivateAboutIndexRouteImport } from './routes/_private/about/index'
import { Route as publicTestIndexRouteImport } from './routes/(public)/test/index'
import { Route as publicForbiddenIndexRouteImport } from './routes/(public)/forbidden/index'
import { Route as ApiTqTodosIdRouteImport } from './routes/api/tq-todos/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as publicTestNoLayoutRouteImport } from './routes/(public)/test_/no-layout'
import { Route as publicTestIdRouteImport } from './routes/(public)/test/$id'
import { Route as PrivateAdminAdminIndexRouteImport } from './routes/_private/_admin/admin/index'
import { Route as publicTestNestedIndexRouteImport } from './routes/(public)/test/nested/index'
import { Route as publicdemoTodos2IndexRouteImport } from './routes/(public)/(demo)/todos2/index'
import { Route as publicdemoTodosIndexRouteImport } from './routes/(public)/(demo)/todos/index'
import { Route as publicdemoTanstackQueryIndexRouteImport } from './routes/(public)/(demo)/tanstack-query/index'
import { Route as publicdemoSuspenseIndexRouteImport } from './routes/(public)/(demo)/suspense/index'
import { Route as publicdemoServerPaginationIndexRouteImport } from './routes/(public)/(demo)/server-pagination/index'
import { Route as publicdemoClientPaginationIndexRouteImport } from './routes/(public)/(demo)/client-pagination/index'
import { Route as publicdemoAwaitWithCatchIndexRouteImport } from './routes/(public)/(demo)/await-with-catch/index'
import { Route as publicauthResetPasswordIndexRouteImport } from './routes/(public)/(auth)/reset-password/index'
import { Route as publicauthRegisterIndexRouteImport } from './routes/(public)/(auth)/register/index'
import { Route as publicauthLoginIndexRouteImport } from './routes/(public)/(auth)/login/index'
import { Route as publicauthForgotPasswordIndexRouteImport } from './routes/(public)/(auth)/forgot-password/index'
import { Route as publicauthEmailChangeStatusIndexRouteImport } from './routes/(public)/(auth)/email-change-status/index'
import { Route as publicTestIdBonusRouteImport } from './routes/(public)/test/$id.bonus'
import { Route as publicdemoTodos2IdRouteImport } from './routes/(public)/(demo)/todos2/$id'
import { Route as publicdemoTodosIdRouteImport } from './routes/(public)/(demo)/todos/$id'
import { Route as publicdemoTanstackQueryIdRouteImport } from './routes/(public)/(demo)/tanstack-query/$id'
import { Route as publicdemoStartApiRequestRouteImport } from './routes/(public)/(demo)/start.api-request'
import { Route as publicdemoOptionalChar123IdChar125RouteImport } from './routes/(public)/(demo)/optional/{-$id}'
import { Route as publicdemoApiNamesRouteImport } from './routes/(public)/(demo)/api.names'
import { Route as PrivateAdminAdminNestedIndexRouteImport } from './routes/_private/_admin/admin/nested/index'
import { Route as publicdemoTanstackQueryUseSuspenseQueryIndexRouteImport } from './routes/(public)/(demo)/tanstack-query/use-suspense-query/index'
import { Route as publicdemoStartSsrIndexRouteImport } from './routes/(public)/(demo)/start.ssr.index'
import { Route as publicdemoStartSsrSpaModeRouteImport } from './routes/(public)/(demo)/start.ssr.spa-mode'
import { Route as publicdemoStartSsrFullSsrRouteImport } from './routes/(public)/(demo)/start.ssr.full-ssr'
import { Route as publicdemoStartSsrDataOnlyRouteImport } from './routes/(public)/(demo)/start.ssr.data-only'
import { Route as publicdemoCatchAllIdSplatRouteImport } from './routes/(public)/(demo)/catch-all/$id.$'

const PrivateRouteRoute = PrivateRouteRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateAdminRouteRoute = PrivateAdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const publicTestRouteRoute = publicTestRouteRouteImport.update({
  id: '/(public)/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTqTodosIndexRoute = ApiTqTodosIndexRouteImport.update({
  id: '/api/tq-todos/',
  path: '/api/tq-todos/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateUserIndexRoute = PrivateUserIndexRouteImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateAboutIndexRoute = PrivateAboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const publicTestIndexRoute = publicTestIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicTestRouteRoute,
} as any)
const publicForbiddenIndexRoute = publicForbiddenIndexRouteImport.update({
  id: '/(public)/forbidden/',
  path: '/forbidden/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTqTodosIdRoute = ApiTqTodosIdRouteImport.update({
  id: '/api/tq-todos/$id',
  path: '/api/tq-todos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const publicTestNoLayoutRoute = publicTestNoLayoutRouteImport.update({
  id: '/(public)/test_/no-layout',
  path: '/test/no-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const publicTestIdRoute = publicTestIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => publicTestRouteRoute,
} as any)
const PrivateAdminAdminIndexRoute = PrivateAdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => PrivateAdminRouteRoute,
} as any)
const publicTestNestedIndexRoute = publicTestNestedIndexRouteImport.update({
  id: '/nested/',
  path: '/nested/',
  getParentRoute: () => publicTestRouteRoute,
} as any)
const publicdemoTodos2IndexRoute = publicdemoTodos2IndexRouteImport.update({
  id: '/(public)/(demo)/todos2/',
  path: '/todos2/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicdemoTodosIndexRoute = publicdemoTodosIndexRouteImport.update({
  id: '/(public)/(demo)/todos/',
  path: '/todos/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicdemoTanstackQueryIndexRoute =
  publicdemoTanstackQueryIndexRouteImport.update({
    id: '/(public)/(demo)/tanstack-query/',
    path: '/tanstack-query/',
    getParentRoute: () => rootRouteImport,
  } as any)
const publicdemoSuspenseIndexRoute = publicdemoSuspenseIndexRouteImport.update({
  id: '/(public)/(demo)/suspense/',
  path: '/suspense/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicdemoServerPaginationIndexRoute =
  publicdemoServerPaginationIndexRouteImport.update({
    id: '/(public)/(demo)/server-pagination/',
    path: '/server-pagination/',
    getParentRoute: () => rootRouteImport,
  } as any)
const publicdemoClientPaginationIndexRoute =
  publicdemoClientPaginationIndexRouteImport.update({
    id: '/(public)/(demo)/client-pagination/',
    path: '/client-pagination/',
    getParentRoute: () => rootRouteImport,
  } as any)
const publicdemoAwaitWithCatchIndexRoute =
  publicdemoAwaitWithCatchIndexRouteImport.update({
    id: '/(public)/(demo)/await-with-catch/',
    path: '/await-with-catch/',
    getParentRoute: () => rootRouteImport,
  } as any)
const publicauthResetPasswordIndexRoute =
  publicauthResetPasswordIndexRouteImport.update({
    id: '/(public)/(auth)/reset-password/',
    path: '/reset-password/',
    getParentRoute: () => rootRouteImport,
  } as any)
const publicauthRegisterIndexRoute = publicauthRegisterIndexRouteImport.update({
  id: '/(public)/(auth)/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicauthLoginIndexRoute = publicauthLoginIndexRouteImport.update({
  id: '/(public)/(auth)/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicauthForgotPasswordIndexRoute =
  publicauthForgotPasswordIndexRouteImport.update({
    id: '/(public)/(auth)/forgot-password/',
    path: '/forgot-password/',
    getParentRoute: () => rootRouteImport,
  } as any)
const publicauthEmailChangeStatusIndexRoute =
  publicauthEmailChangeStatusIndexRouteImport.update({
    id: '/(public)/(auth)/email-change-status/',
    path: '/email-change-status/',
    getParentRoute: () => rootRouteImport,
  } as any)
const publicTestIdBonusRoute = publicTestIdBonusRouteImport.update({
  id: '/bonus',
  path: '/bonus',
  getParentRoute: () => publicTestIdRoute,
} as any)
const publicdemoTodos2IdRoute = publicdemoTodos2IdRouteImport.update({
  id: '/(public)/(demo)/todos2/$id',
  path: '/todos2/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const publicdemoTodosIdRoute = publicdemoTodosIdRouteImport.update({
  id: '/(public)/(demo)/todos/$id',
  path: '/todos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const publicdemoTanstackQueryIdRoute =
  publicdemoTanstackQueryIdRouteImport.update({
    id: '/(public)/(demo)/tanstack-query/$id',
    path: '/tanstack-query/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const publicdemoStartApiRequestRoute =
  publicdemoStartApiRequestRouteImport.update({
    id: '/(public)/(demo)/start/api-request',
    path: '/start/api-request',
    getParentRoute: () => rootRouteImport,
  } as any)
const publicdemoOptionalChar123IdChar125Route =
  publicdemoOptionalChar123IdChar125RouteImport.update({
    id: '/(public)/(demo)/optional/{-$id}',
    path: '/optional/{-$id}',
    getParentRoute: () => rootRouteImport,
  } as any)
const publicdemoApiNamesRoute = publicdemoApiNamesRouteImport.update({
  id: '/(public)/(demo)/api/names',
  path: '/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateAdminAdminNestedIndexRoute =
  PrivateAdminAdminNestedIndexRouteImport.update({
    id: '/admin/nested/',
    path: '/admin/nested/',
    getParentRoute: () => PrivateAdminRouteRoute,
  } as any)
const publicdemoTanstackQueryUseSuspenseQueryIndexRoute =
  publicdemoTanstackQueryUseSuspenseQueryIndexRouteImport.update({
    id: '/(public)/(demo)/tanstack-query/use-suspense-query/',
    path: '/tanstack-query/use-suspense-query/',
    getParentRoute: () => rootRouteImport,
  } as any)
const publicdemoStartSsrIndexRoute = publicdemoStartSsrIndexRouteImport.update({
  id: '/(public)/(demo)/start/ssr/',
  path: '/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicdemoStartSsrSpaModeRoute =
  publicdemoStartSsrSpaModeRouteImport.update({
    id: '/(public)/(demo)/start/ssr/spa-mode',
    path: '/start/ssr/spa-mode',
    getParentRoute: () => rootRouteImport,
  } as any)
const publicdemoStartSsrFullSsrRoute =
  publicdemoStartSsrFullSsrRouteImport.update({
    id: '/(public)/(demo)/start/ssr/full-ssr',
    path: '/start/ssr/full-ssr',
    getParentRoute: () => rootRouteImport,
  } as any)
const publicdemoStartSsrDataOnlyRoute =
  publicdemoStartSsrDataOnlyRouteImport.update({
    id: '/(public)/(demo)/start/ssr/data-only',
    path: '/start/ssr/data-only',
    getParentRoute: () => rootRouteImport,
  } as any)
const publicdemoCatchAllIdSplatRoute =
  publicdemoCatchAllIdSplatRouteImport.update({
    id: '/(public)/(demo)/catch-all/$id/$',
    path: '/catch-all/$id/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/test': typeof publicTestRouteRouteWithChildren
  '/test/$id': typeof publicTestIdRouteWithChildren
  '/test/no-layout': typeof publicTestNoLayoutRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/tq-todos/$id': typeof ApiTqTodosIdRoute
  '/forbidden/': typeof publicForbiddenIndexRoute
  '/test/': typeof publicTestIndexRoute
  '/about/': typeof PrivateAboutIndexRoute
  '/user/': typeof PrivateUserIndexRoute
  '/api/tq-todos/': typeof ApiTqTodosIndexRoute
  '/api/names': typeof publicdemoApiNamesRoute
  '/optional/{-$id}': typeof publicdemoOptionalChar123IdChar125Route
  '/start/api-request': typeof publicdemoStartApiRequestRoute
  '/tanstack-query/$id': typeof publicdemoTanstackQueryIdRoute
  '/todos/$id': typeof publicdemoTodosIdRoute
  '/todos2/$id': typeof publicdemoTodos2IdRoute
  '/test/$id/bonus': typeof publicTestIdBonusRoute
  '/email-change-status/': typeof publicauthEmailChangeStatusIndexRoute
  '/forgot-password/': typeof publicauthForgotPasswordIndexRoute
  '/login/': typeof publicauthLoginIndexRoute
  '/register/': typeof publicauthRegisterIndexRoute
  '/reset-password/': typeof publicauthResetPasswordIndexRoute
  '/await-with-catch/': typeof publicdemoAwaitWithCatchIndexRoute
  '/client-pagination/': typeof publicdemoClientPaginationIndexRoute
  '/server-pagination/': typeof publicdemoServerPaginationIndexRoute
  '/suspense/': typeof publicdemoSuspenseIndexRoute
  '/tanstack-query/': typeof publicdemoTanstackQueryIndexRoute
  '/todos/': typeof publicdemoTodosIndexRoute
  '/todos2/': typeof publicdemoTodos2IndexRoute
  '/test/nested/': typeof publicTestNestedIndexRoute
  '/admin/': typeof PrivateAdminAdminIndexRoute
  '/catch-all/$id/$': typeof publicdemoCatchAllIdSplatRoute
  '/start/ssr/data-only': typeof publicdemoStartSsrDataOnlyRoute
  '/start/ssr/full-ssr': typeof publicdemoStartSsrFullSsrRoute
  '/start/ssr/spa-mode': typeof publicdemoStartSsrSpaModeRoute
  '/start/ssr/': typeof publicdemoStartSsrIndexRoute
  '/tanstack-query/use-suspense-query/': typeof publicdemoTanstackQueryUseSuspenseQueryIndexRoute
  '/admin/nested/': typeof PrivateAdminAdminNestedIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/test/$id': typeof publicTestIdRouteWithChildren
  '/test/no-layout': typeof publicTestNoLayoutRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/tq-todos/$id': typeof ApiTqTodosIdRoute
  '/forbidden': typeof publicForbiddenIndexRoute
  '/test': typeof publicTestIndexRoute
  '/about': typeof PrivateAboutIndexRoute
  '/user': typeof PrivateUserIndexRoute
  '/api/tq-todos': typeof ApiTqTodosIndexRoute
  '/api/names': typeof publicdemoApiNamesRoute
  '/optional/{-$id}': typeof publicdemoOptionalChar123IdChar125Route
  '/start/api-request': typeof publicdemoStartApiRequestRoute
  '/tanstack-query/$id': typeof publicdemoTanstackQueryIdRoute
  '/todos/$id': typeof publicdemoTodosIdRoute
  '/todos2/$id': typeof publicdemoTodos2IdRoute
  '/test/$id/bonus': typeof publicTestIdBonusRoute
  '/email-change-status': typeof publicauthEmailChangeStatusIndexRoute
  '/forgot-password': typeof publicauthForgotPasswordIndexRoute
  '/login': typeof publicauthLoginIndexRoute
  '/register': typeof publicauthRegisterIndexRoute
  '/reset-password': typeof publicauthResetPasswordIndexRoute
  '/await-with-catch': typeof publicdemoAwaitWithCatchIndexRoute
  '/client-pagination': typeof publicdemoClientPaginationIndexRoute
  '/server-pagination': typeof publicdemoServerPaginationIndexRoute
  '/suspense': typeof publicdemoSuspenseIndexRoute
  '/tanstack-query': typeof publicdemoTanstackQueryIndexRoute
  '/todos': typeof publicdemoTodosIndexRoute
  '/todos2': typeof publicdemoTodos2IndexRoute
  '/test/nested': typeof publicTestNestedIndexRoute
  '/admin': typeof PrivateAdminAdminIndexRoute
  '/catch-all/$id/$': typeof publicdemoCatchAllIdSplatRoute
  '/start/ssr/data-only': typeof publicdemoStartSsrDataOnlyRoute
  '/start/ssr/full-ssr': typeof publicdemoStartSsrFullSsrRoute
  '/start/ssr/spa-mode': typeof publicdemoStartSsrSpaModeRoute
  '/start/ssr': typeof publicdemoStartSsrIndexRoute
  '/tanstack-query/use-suspense-query': typeof publicdemoTanstackQueryUseSuspenseQueryIndexRoute
  '/admin/nested': typeof PrivateAdminAdminNestedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_private': typeof PrivateRouteRouteWithChildren
  '/(public)/test': typeof publicTestRouteRouteWithChildren
  '/_private/_admin': typeof PrivateAdminRouteRouteWithChildren
  '/(public)/test/$id': typeof publicTestIdRouteWithChildren
  '/(public)/test_/no-layout': typeof publicTestNoLayoutRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/tq-todos/$id': typeof ApiTqTodosIdRoute
  '/(public)/forbidden/': typeof publicForbiddenIndexRoute
  '/(public)/test/': typeof publicTestIndexRoute
  '/_private/about/': typeof PrivateAboutIndexRoute
  '/_private/user/': typeof PrivateUserIndexRoute
  '/api/tq-todos/': typeof ApiTqTodosIndexRoute
  '/(public)/(demo)/api/names': typeof publicdemoApiNamesRoute
  '/(public)/(demo)/optional/{-$id}': typeof publicdemoOptionalChar123IdChar125Route
  '/(public)/(demo)/start/api-request': typeof publicdemoStartApiRequestRoute
  '/(public)/(demo)/tanstack-query/$id': typeof publicdemoTanstackQueryIdRoute
  '/(public)/(demo)/todos/$id': typeof publicdemoTodosIdRoute
  '/(public)/(demo)/todos2/$id': typeof publicdemoTodos2IdRoute
  '/(public)/test/$id/bonus': typeof publicTestIdBonusRoute
  '/(public)/(auth)/email-change-status/': typeof publicauthEmailChangeStatusIndexRoute
  '/(public)/(auth)/forgot-password/': typeof publicauthForgotPasswordIndexRoute
  '/(public)/(auth)/login/': typeof publicauthLoginIndexRoute
  '/(public)/(auth)/register/': typeof publicauthRegisterIndexRoute
  '/(public)/(auth)/reset-password/': typeof publicauthResetPasswordIndexRoute
  '/(public)/(demo)/await-with-catch/': typeof publicdemoAwaitWithCatchIndexRoute
  '/(public)/(demo)/client-pagination/': typeof publicdemoClientPaginationIndexRoute
  '/(public)/(demo)/server-pagination/': typeof publicdemoServerPaginationIndexRoute
  '/(public)/(demo)/suspense/': typeof publicdemoSuspenseIndexRoute
  '/(public)/(demo)/tanstack-query/': typeof publicdemoTanstackQueryIndexRoute
  '/(public)/(demo)/todos/': typeof publicdemoTodosIndexRoute
  '/(public)/(demo)/todos2/': typeof publicdemoTodos2IndexRoute
  '/(public)/test/nested/': typeof publicTestNestedIndexRoute
  '/_private/_admin/admin/': typeof PrivateAdminAdminIndexRoute
  '/(public)/(demo)/catch-all/$id/$': typeof publicdemoCatchAllIdSplatRoute
  '/(public)/(demo)/start/ssr/data-only': typeof publicdemoStartSsrDataOnlyRoute
  '/(public)/(demo)/start/ssr/full-ssr': typeof publicdemoStartSsrFullSsrRoute
  '/(public)/(demo)/start/ssr/spa-mode': typeof publicdemoStartSsrSpaModeRoute
  '/(public)/(demo)/start/ssr/': typeof publicdemoStartSsrIndexRoute
  '/(public)/(demo)/tanstack-query/use-suspense-query/': typeof publicdemoTanstackQueryUseSuspenseQueryIndexRoute
  '/_private/_admin/admin/nested/': typeof PrivateAdminAdminNestedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/test'
    | '/test/$id'
    | '/test/no-layout'
    | '/api/auth/$'
    | '/api/tq-todos/$id'
    | '/forbidden/'
    | '/test/'
    | '/about/'
    | '/user/'
    | '/api/tq-todos/'
    | '/api/names'
    | '/optional/{-$id}'
    | '/start/api-request'
    | '/tanstack-query/$id'
    | '/todos/$id'
    | '/todos2/$id'
    | '/test/$id/bonus'
    | '/email-change-status/'
    | '/forgot-password/'
    | '/login/'
    | '/register/'
    | '/reset-password/'
    | '/await-with-catch/'
    | '/client-pagination/'
    | '/server-pagination/'
    | '/suspense/'
    | '/tanstack-query/'
    | '/todos/'
    | '/todos2/'
    | '/test/nested/'
    | '/admin/'
    | '/catch-all/$id/$'
    | '/start/ssr/data-only'
    | '/start/ssr/full-ssr'
    | '/start/ssr/spa-mode'
    | '/start/ssr/'
    | '/tanstack-query/use-suspense-query/'
    | '/admin/nested/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/test/$id'
    | '/test/no-layout'
    | '/api/auth/$'
    | '/api/tq-todos/$id'
    | '/forbidden'
    | '/test'
    | '/about'
    | '/user'
    | '/api/tq-todos'
    | '/api/names'
    | '/optional/{-$id}'
    | '/start/api-request'
    | '/tanstack-query/$id'
    | '/todos/$id'
    | '/todos2/$id'
    | '/test/$id/bonus'
    | '/email-change-status'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/await-with-catch'
    | '/client-pagination'
    | '/server-pagination'
    | '/suspense'
    | '/tanstack-query'
    | '/todos'
    | '/todos2'
    | '/test/nested'
    | '/admin'
    | '/catch-all/$id/$'
    | '/start/ssr/data-only'
    | '/start/ssr/full-ssr'
    | '/start/ssr/spa-mode'
    | '/start/ssr'
    | '/tanstack-query/use-suspense-query'
    | '/admin/nested'
  id:
    | '__root__'
    | '/'
    | '/_private'
    | '/(public)/test'
    | '/_private/_admin'
    | '/(public)/test/$id'
    | '/(public)/test_/no-layout'
    | '/api/auth/$'
    | '/api/tq-todos/$id'
    | '/(public)/forbidden/'
    | '/(public)/test/'
    | '/_private/about/'
    | '/_private/user/'
    | '/api/tq-todos/'
    | '/(public)/(demo)/api/names'
    | '/(public)/(demo)/optional/{-$id}'
    | '/(public)/(demo)/start/api-request'
    | '/(public)/(demo)/tanstack-query/$id'
    | '/(public)/(demo)/todos/$id'
    | '/(public)/(demo)/todos2/$id'
    | '/(public)/test/$id/bonus'
    | '/(public)/(auth)/email-change-status/'
    | '/(public)/(auth)/forgot-password/'
    | '/(public)/(auth)/login/'
    | '/(public)/(auth)/register/'
    | '/(public)/(auth)/reset-password/'
    | '/(public)/(demo)/await-with-catch/'
    | '/(public)/(demo)/client-pagination/'
    | '/(public)/(demo)/server-pagination/'
    | '/(public)/(demo)/suspense/'
    | '/(public)/(demo)/tanstack-query/'
    | '/(public)/(demo)/todos/'
    | '/(public)/(demo)/todos2/'
    | '/(public)/test/nested/'
    | '/_private/_admin/admin/'
    | '/(public)/(demo)/catch-all/$id/$'
    | '/(public)/(demo)/start/ssr/data-only'
    | '/(public)/(demo)/start/ssr/full-ssr'
    | '/(public)/(demo)/start/ssr/spa-mode'
    | '/(public)/(demo)/start/ssr/'
    | '/(public)/(demo)/tanstack-query/use-suspense-query/'
    | '/_private/_admin/admin/nested/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivateRouteRoute: typeof PrivateRouteRouteWithChildren
  publicTestRouteRoute: typeof publicTestRouteRouteWithChildren
  publicTestNoLayoutRoute: typeof publicTestNoLayoutRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTqTodosIdRoute: typeof ApiTqTodosIdRoute
  publicForbiddenIndexRoute: typeof publicForbiddenIndexRoute
  ApiTqTodosIndexRoute: typeof ApiTqTodosIndexRoute
  publicdemoApiNamesRoute: typeof publicdemoApiNamesRoute
  publicdemoOptionalChar123IdChar125Route: typeof publicdemoOptionalChar123IdChar125Route
  publicdemoStartApiRequestRoute: typeof publicdemoStartApiRequestRoute
  publicdemoTanstackQueryIdRoute: typeof publicdemoTanstackQueryIdRoute
  publicdemoTodosIdRoute: typeof publicdemoTodosIdRoute
  publicdemoTodos2IdRoute: typeof publicdemoTodos2IdRoute
  publicauthEmailChangeStatusIndexRoute: typeof publicauthEmailChangeStatusIndexRoute
  publicauthForgotPasswordIndexRoute: typeof publicauthForgotPasswordIndexRoute
  publicauthLoginIndexRoute: typeof publicauthLoginIndexRoute
  publicauthRegisterIndexRoute: typeof publicauthRegisterIndexRoute
  publicauthResetPasswordIndexRoute: typeof publicauthResetPasswordIndexRoute
  publicdemoAwaitWithCatchIndexRoute: typeof publicdemoAwaitWithCatchIndexRoute
  publicdemoClientPaginationIndexRoute: typeof publicdemoClientPaginationIndexRoute
  publicdemoServerPaginationIndexRoute: typeof publicdemoServerPaginationIndexRoute
  publicdemoSuspenseIndexRoute: typeof publicdemoSuspenseIndexRoute
  publicdemoTanstackQueryIndexRoute: typeof publicdemoTanstackQueryIndexRoute
  publicdemoTodosIndexRoute: typeof publicdemoTodosIndexRoute
  publicdemoTodos2IndexRoute: typeof publicdemoTodos2IndexRoute
  publicdemoCatchAllIdSplatRoute: typeof publicdemoCatchAllIdSplatRoute
  publicdemoStartSsrDataOnlyRoute: typeof publicdemoStartSsrDataOnlyRoute
  publicdemoStartSsrFullSsrRoute: typeof publicdemoStartSsrFullSsrRoute
  publicdemoStartSsrSpaModeRoute: typeof publicdemoStartSsrSpaModeRoute
  publicdemoStartSsrIndexRoute: typeof publicdemoStartSsrIndexRoute
  publicdemoTanstackQueryUseSuspenseQueryIndexRoute: typeof publicdemoTanstackQueryUseSuspenseQueryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/_admin': {
      id: '/_private/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateAdminRouteRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/(public)/test': {
      id: '/(public)/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof publicTestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tq-todos/': {
      id: '/api/tq-todos/'
      path: '/api/tq-todos'
      fullPath: '/api/tq-todos/'
      preLoaderRoute: typeof ApiTqTodosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/user/': {
      id: '/_private/user/'
      path: '/user'
      fullPath: '/user/'
      preLoaderRoute: typeof PrivateUserIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/about/': {
      id: '/_private/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof PrivateAboutIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/(public)/test/': {
      id: '/(public)/test/'
      path: '/'
      fullPath: '/test/'
      preLoaderRoute: typeof publicTestIndexRouteImport
      parentRoute: typeof publicTestRouteRoute
    }
    '/(public)/forbidden/': {
      id: '/(public)/forbidden/'
      path: '/forbidden'
      fullPath: '/forbidden/'
      preLoaderRoute: typeof publicForbiddenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tq-todos/$id': {
      id: '/api/tq-todos/$id'
      path: '/api/tq-todos/$id'
      fullPath: '/api/tq-todos/$id'
      preLoaderRoute: typeof ApiTqTodosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/test_/no-layout': {
      id: '/(public)/test_/no-layout'
      path: '/test/no-layout'
      fullPath: '/test/no-layout'
      preLoaderRoute: typeof publicTestNoLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/test/$id': {
      id: '/(public)/test/$id'
      path: '/$id'
      fullPath: '/test/$id'
      preLoaderRoute: typeof publicTestIdRouteImport
      parentRoute: typeof publicTestRouteRoute
    }
    '/_private/_admin/admin/': {
      id: '/_private/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof PrivateAdminAdminIndexRouteImport
      parentRoute: typeof PrivateAdminRouteRoute
    }
    '/(public)/test/nested/': {
      id: '/(public)/test/nested/'
      path: '/nested'
      fullPath: '/test/nested/'
      preLoaderRoute: typeof publicTestNestedIndexRouteImport
      parentRoute: typeof publicTestRouteRoute
    }
    '/(public)/(demo)/todos2/': {
      id: '/(public)/(demo)/todos2/'
      path: '/todos2'
      fullPath: '/todos2/'
      preLoaderRoute: typeof publicdemoTodos2IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/(demo)/todos/': {
      id: '/(public)/(demo)/todos/'
      path: '/todos'
      fullPath: '/todos/'
      preLoaderRoute: typeof publicdemoTodosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/(demo)/tanstack-query/': {
      id: '/(public)/(demo)/tanstack-query/'
      path: '/tanstack-query'
      fullPath: '/tanstack-query/'
      preLoaderRoute: typeof publicdemoTanstackQueryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/(demo)/suspense/': {
      id: '/(public)/(demo)/suspense/'
      path: '/suspense'
      fullPath: '/suspense/'
      preLoaderRoute: typeof publicdemoSuspenseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/(demo)/server-pagination/': {
      id: '/(public)/(demo)/server-pagination/'
      path: '/server-pagination'
      fullPath: '/server-pagination/'
      preLoaderRoute: typeof publicdemoServerPaginationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/(demo)/client-pagination/': {
      id: '/(public)/(demo)/client-pagination/'
      path: '/client-pagination'
      fullPath: '/client-pagination/'
      preLoaderRoute: typeof publicdemoClientPaginationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/(demo)/await-with-catch/': {
      id: '/(public)/(demo)/await-with-catch/'
      path: '/await-with-catch'
      fullPath: '/await-with-catch/'
      preLoaderRoute: typeof publicdemoAwaitWithCatchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/(auth)/reset-password/': {
      id: '/(public)/(auth)/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password/'
      preLoaderRoute: typeof publicauthResetPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/(auth)/register/': {
      id: '/(public)/(auth)/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof publicauthRegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/(auth)/login/': {
      id: '/(public)/(auth)/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof publicauthLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/(auth)/forgot-password/': {
      id: '/(public)/(auth)/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password/'
      preLoaderRoute: typeof publicauthForgotPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/(auth)/email-change-status/': {
      id: '/(public)/(auth)/email-change-status/'
      path: '/email-change-status'
      fullPath: '/email-change-status/'
      preLoaderRoute: typeof publicauthEmailChangeStatusIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/test/$id/bonus': {
      id: '/(public)/test/$id/bonus'
      path: '/bonus'
      fullPath: '/test/$id/bonus'
      preLoaderRoute: typeof publicTestIdBonusRouteImport
      parentRoute: typeof publicTestIdRoute
    }
    '/(public)/(demo)/todos2/$id': {
      id: '/(public)/(demo)/todos2/$id'
      path: '/todos2/$id'
      fullPath: '/todos2/$id'
      preLoaderRoute: typeof publicdemoTodos2IdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/(demo)/todos/$id': {
      id: '/(public)/(demo)/todos/$id'
      path: '/todos/$id'
      fullPath: '/todos/$id'
      preLoaderRoute: typeof publicdemoTodosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/(demo)/tanstack-query/$id': {
      id: '/(public)/(demo)/tanstack-query/$id'
      path: '/tanstack-query/$id'
      fullPath: '/tanstack-query/$id'
      preLoaderRoute: typeof publicdemoTanstackQueryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/(demo)/start/api-request': {
      id: '/(public)/(demo)/start/api-request'
      path: '/start/api-request'
      fullPath: '/start/api-request'
      preLoaderRoute: typeof publicdemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/(demo)/optional/{-$id}': {
      id: '/(public)/(demo)/optional/{-$id}'
      path: '/optional/{-$id}'
      fullPath: '/optional/{-$id}'
      preLoaderRoute: typeof publicdemoOptionalChar123IdChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/(demo)/api/names': {
      id: '/(public)/(demo)/api/names'
      path: '/api/names'
      fullPath: '/api/names'
      preLoaderRoute: typeof publicdemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/_admin/admin/nested/': {
      id: '/_private/_admin/admin/nested/'
      path: '/admin/nested'
      fullPath: '/admin/nested/'
      preLoaderRoute: typeof PrivateAdminAdminNestedIndexRouteImport
      parentRoute: typeof PrivateAdminRouteRoute
    }
    '/(public)/(demo)/tanstack-query/use-suspense-query/': {
      id: '/(public)/(demo)/tanstack-query/use-suspense-query/'
      path: '/tanstack-query/use-suspense-query'
      fullPath: '/tanstack-query/use-suspense-query/'
      preLoaderRoute: typeof publicdemoTanstackQueryUseSuspenseQueryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/(demo)/start/ssr/': {
      id: '/(public)/(demo)/start/ssr/'
      path: '/start/ssr'
      fullPath: '/start/ssr/'
      preLoaderRoute: typeof publicdemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/(demo)/start/ssr/spa-mode': {
      id: '/(public)/(demo)/start/ssr/spa-mode'
      path: '/start/ssr/spa-mode'
      fullPath: '/start/ssr/spa-mode'
      preLoaderRoute: typeof publicdemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/(demo)/start/ssr/full-ssr': {
      id: '/(public)/(demo)/start/ssr/full-ssr'
      path: '/start/ssr/full-ssr'
      fullPath: '/start/ssr/full-ssr'
      preLoaderRoute: typeof publicdemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/(demo)/start/ssr/data-only': {
      id: '/(public)/(demo)/start/ssr/data-only'
      path: '/start/ssr/data-only'
      fullPath: '/start/ssr/data-only'
      preLoaderRoute: typeof publicdemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/(demo)/catch-all/$id/$': {
      id: '/(public)/(demo)/catch-all/$id/$'
      path: '/catch-all/$id/$'
      fullPath: '/catch-all/$id/$'
      preLoaderRoute: typeof publicdemoCatchAllIdSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PrivateAdminRouteRouteChildren {
  PrivateAdminAdminIndexRoute: typeof PrivateAdminAdminIndexRoute
  PrivateAdminAdminNestedIndexRoute: typeof PrivateAdminAdminNestedIndexRoute
}

const PrivateAdminRouteRouteChildren: PrivateAdminRouteRouteChildren = {
  PrivateAdminAdminIndexRoute: PrivateAdminAdminIndexRoute,
  PrivateAdminAdminNestedIndexRoute: PrivateAdminAdminNestedIndexRoute,
}

const PrivateAdminRouteRouteWithChildren =
  PrivateAdminRouteRoute._addFileChildren(PrivateAdminRouteRouteChildren)

interface PrivateRouteRouteChildren {
  PrivateAdminRouteRoute: typeof PrivateAdminRouteRouteWithChildren
  PrivateAboutIndexRoute: typeof PrivateAboutIndexRoute
  PrivateUserIndexRoute: typeof PrivateUserIndexRoute
}

const PrivateRouteRouteChildren: PrivateRouteRouteChildren = {
  PrivateAdminRouteRoute: PrivateAdminRouteRouteWithChildren,
  PrivateAboutIndexRoute: PrivateAboutIndexRoute,
  PrivateUserIndexRoute: PrivateUserIndexRoute,
}

const PrivateRouteRouteWithChildren = PrivateRouteRoute._addFileChildren(
  PrivateRouteRouteChildren,
)

interface publicTestIdRouteChildren {
  publicTestIdBonusRoute: typeof publicTestIdBonusRoute
}

const publicTestIdRouteChildren: publicTestIdRouteChildren = {
  publicTestIdBonusRoute: publicTestIdBonusRoute,
}

const publicTestIdRouteWithChildren = publicTestIdRoute._addFileChildren(
  publicTestIdRouteChildren,
)

interface publicTestRouteRouteChildren {
  publicTestIdRoute: typeof publicTestIdRouteWithChildren
  publicTestIndexRoute: typeof publicTestIndexRoute
  publicTestNestedIndexRoute: typeof publicTestNestedIndexRoute
}

const publicTestRouteRouteChildren: publicTestRouteRouteChildren = {
  publicTestIdRoute: publicTestIdRouteWithChildren,
  publicTestIndexRoute: publicTestIndexRoute,
  publicTestNestedIndexRoute: publicTestNestedIndexRoute,
}

const publicTestRouteRouteWithChildren = publicTestRouteRoute._addFileChildren(
  publicTestRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivateRouteRoute: PrivateRouteRouteWithChildren,
  publicTestRouteRoute: publicTestRouteRouteWithChildren,
  publicTestNoLayoutRoute: publicTestNoLayoutRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTqTodosIdRoute: ApiTqTodosIdRoute,
  publicForbiddenIndexRoute: publicForbiddenIndexRoute,
  ApiTqTodosIndexRoute: ApiTqTodosIndexRoute,
  publicdemoApiNamesRoute: publicdemoApiNamesRoute,
  publicdemoOptionalChar123IdChar125Route:
    publicdemoOptionalChar123IdChar125Route,
  publicdemoStartApiRequestRoute: publicdemoStartApiRequestRoute,
  publicdemoTanstackQueryIdRoute: publicdemoTanstackQueryIdRoute,
  publicdemoTodosIdRoute: publicdemoTodosIdRoute,
  publicdemoTodos2IdRoute: publicdemoTodos2IdRoute,
  publicauthEmailChangeStatusIndexRoute: publicauthEmailChangeStatusIndexRoute,
  publicauthForgotPasswordIndexRoute: publicauthForgotPasswordIndexRoute,
  publicauthLoginIndexRoute: publicauthLoginIndexRoute,
  publicauthRegisterIndexRoute: publicauthRegisterIndexRoute,
  publicauthResetPasswordIndexRoute: publicauthResetPasswordIndexRoute,
  publicdemoAwaitWithCatchIndexRoute: publicdemoAwaitWithCatchIndexRoute,
  publicdemoClientPaginationIndexRoute: publicdemoClientPaginationIndexRoute,
  publicdemoServerPaginationIndexRoute: publicdemoServerPaginationIndexRoute,
  publicdemoSuspenseIndexRoute: publicdemoSuspenseIndexRoute,
  publicdemoTanstackQueryIndexRoute: publicdemoTanstackQueryIndexRoute,
  publicdemoTodosIndexRoute: publicdemoTodosIndexRoute,
  publicdemoTodos2IndexRoute: publicdemoTodos2IndexRoute,
  publicdemoCatchAllIdSplatRoute: publicdemoCatchAllIdSplatRoute,
  publicdemoStartSsrDataOnlyRoute: publicdemoStartSsrDataOnlyRoute,
  publicdemoStartSsrFullSsrRoute: publicdemoStartSsrFullSsrRoute,
  publicdemoStartSsrSpaModeRoute: publicdemoStartSsrSpaModeRoute,
  publicdemoStartSsrIndexRoute: publicdemoStartSsrIndexRoute,
  publicdemoTanstackQueryUseSuspenseQueryIndexRoute:
    publicdemoTanstackQueryUseSuspenseQueryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
