/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteRouteImport } from './routes/test/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestIndexRouteImport } from './routes/test/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as TestNoLayoutRouteImport } from './routes/test_/no-layout'
import { Route as TestIdRouteImport } from './routes/test/$id'
import { Route as TestNestedIndexRouteImport } from './routes/test/nested/index'
import { Route as ApiTqTodosIndexRouteImport } from './routes/api/tq-todos/index'
import { Route as demoUsersIndexRouteImport } from './routes/(demo)/users/index'
import { Route as demoTodos2IndexRouteImport } from './routes/(demo)/todos2/index'
import { Route as demoTodosIndexRouteImport } from './routes/(demo)/todos/index'
import { Route as demoTanstackQueryIndexRouteImport } from './routes/(demo)/tanstack-query/index'
import { Route as demoSuspenseIndexRouteImport } from './routes/(demo)/suspense/index'
import { Route as demoServerPaginationIndexRouteImport } from './routes/(demo)/server-pagination/index'
import { Route as demoAwaitWithCatchIndexRouteImport } from './routes/(demo)/await-with-catch/index'
import { Route as TestIdBonusRouteImport } from './routes/test/$id.bonus'
import { Route as ApiTqTodosIdRouteImport } from './routes/api/tq-todos/$id'
import { Route as demoUsersIdRouteImport } from './routes/(demo)/users/$id'
import { Route as demoTodos2IdRouteImport } from './routes/(demo)/todos2/$id'
import { Route as demoTodosIdRouteImport } from './routes/(demo)/todos/$id'
import { Route as demoTanstackQueryIdRouteImport } from './routes/(demo)/tanstack-query/$id'
import { Route as demoStartApiRequestRouteImport } from './routes/(demo)/start.api-request'
import { Route as demoOptionalChar123IdChar125RouteImport } from './routes/(demo)/optional/{-$id}'
import { Route as demoApiNamesRouteImport } from './routes/(demo)/api.names'
import { Route as demoTanstackQueryUseSuspenseQueryIndexRouteImport } from './routes/(demo)/tanstack-query/use-suspense-query/index'
import { Route as demoStartSsrIndexRouteImport } from './routes/(demo)/start.ssr.index'
import { Route as demoStartSsrSpaModeRouteImport } from './routes/(demo)/start.ssr.spa-mode'
import { Route as demoStartSsrFullSsrRouteImport } from './routes/(demo)/start.ssr.full-ssr'
import { Route as demoStartSsrDataOnlyRouteImport } from './routes/(demo)/start.ssr.data-only'
import { Route as demoCatchAllIdSplatRouteImport } from './routes/(demo)/catch-all/$id.$'

const TestRouteRoute = TestRouteRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestIndexRoute = TestIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TestRouteRoute,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestNoLayoutRoute = TestNoLayoutRouteImport.update({
  id: '/test_/no-layout',
  path: '/test/no-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const TestIdRoute = TestIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TestRouteRoute,
} as any)
const TestNestedIndexRoute = TestNestedIndexRouteImport.update({
  id: '/nested/',
  path: '/nested/',
  getParentRoute: () => TestRouteRoute,
} as any)
const ApiTqTodosIndexRoute = ApiTqTodosIndexRouteImport.update({
  id: '/api/tq-todos/',
  path: '/api/tq-todos/',
  getParentRoute: () => rootRouteImport,
} as any)
const demoUsersIndexRoute = demoUsersIndexRouteImport.update({
  id: '/(demo)/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const demoTodos2IndexRoute = demoTodos2IndexRouteImport.update({
  id: '/(demo)/todos2/',
  path: '/todos2/',
  getParentRoute: () => rootRouteImport,
} as any)
const demoTodosIndexRoute = demoTodosIndexRouteImport.update({
  id: '/(demo)/todos/',
  path: '/todos/',
  getParentRoute: () => rootRouteImport,
} as any)
const demoTanstackQueryIndexRoute = demoTanstackQueryIndexRouteImport.update({
  id: '/(demo)/tanstack-query/',
  path: '/tanstack-query/',
  getParentRoute: () => rootRouteImport,
} as any)
const demoSuspenseIndexRoute = demoSuspenseIndexRouteImport.update({
  id: '/(demo)/suspense/',
  path: '/suspense/',
  getParentRoute: () => rootRouteImport,
} as any)
const demoServerPaginationIndexRoute =
  demoServerPaginationIndexRouteImport.update({
    id: '/(demo)/server-pagination/',
    path: '/server-pagination/',
    getParentRoute: () => rootRouteImport,
  } as any)
const demoAwaitWithCatchIndexRoute = demoAwaitWithCatchIndexRouteImport.update({
  id: '/(demo)/await-with-catch/',
  path: '/await-with-catch/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestIdBonusRoute = TestIdBonusRouteImport.update({
  id: '/bonus',
  path: '/bonus',
  getParentRoute: () => TestIdRoute,
} as any)
const ApiTqTodosIdRoute = ApiTqTodosIdRouteImport.update({
  id: '/api/tq-todos/$id',
  path: '/api/tq-todos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const demoUsersIdRoute = demoUsersIdRouteImport.update({
  id: '/(demo)/users/$id',
  path: '/users/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const demoTodos2IdRoute = demoTodos2IdRouteImport.update({
  id: '/(demo)/todos2/$id',
  path: '/todos2/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const demoTodosIdRoute = demoTodosIdRouteImport.update({
  id: '/(demo)/todos/$id',
  path: '/todos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const demoTanstackQueryIdRoute = demoTanstackQueryIdRouteImport.update({
  id: '/(demo)/tanstack-query/$id',
  path: '/tanstack-query/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const demoStartApiRequestRoute = demoStartApiRequestRouteImport.update({
  id: '/(demo)/start/api-request',
  path: '/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const demoOptionalChar123IdChar125Route =
  demoOptionalChar123IdChar125RouteImport.update({
    id: '/(demo)/optional/{-$id}',
    path: '/optional/{-$id}',
    getParentRoute: () => rootRouteImport,
  } as any)
const demoApiNamesRoute = demoApiNamesRouteImport.update({
  id: '/(demo)/api/names',
  path: '/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const demoTanstackQueryUseSuspenseQueryIndexRoute =
  demoTanstackQueryUseSuspenseQueryIndexRouteImport.update({
    id: '/(demo)/tanstack-query/use-suspense-query/',
    path: '/tanstack-query/use-suspense-query/',
    getParentRoute: () => rootRouteImport,
  } as any)
const demoStartSsrIndexRoute = demoStartSsrIndexRouteImport.update({
  id: '/(demo)/start/ssr/',
  path: '/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const demoStartSsrSpaModeRoute = demoStartSsrSpaModeRouteImport.update({
  id: '/(demo)/start/ssr/spa-mode',
  path: '/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const demoStartSsrFullSsrRoute = demoStartSsrFullSsrRouteImport.update({
  id: '/(demo)/start/ssr/full-ssr',
  path: '/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const demoStartSsrDataOnlyRoute = demoStartSsrDataOnlyRouteImport.update({
  id: '/(demo)/start/ssr/data-only',
  path: '/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)
const demoCatchAllIdSplatRoute = demoCatchAllIdSplatRouteImport.update({
  id: '/(demo)/catch-all/$id/$',
  path: '/catch-all/$id/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/test': typeof TestRouteRouteWithChildren
  '/test/$id': typeof TestIdRouteWithChildren
  '/test/no-layout': typeof TestNoLayoutRoute
  '/about/': typeof AboutIndexRoute
  '/test/': typeof TestIndexRoute
  '/api/names': typeof demoApiNamesRoute
  '/optional/{-$id}': typeof demoOptionalChar123IdChar125Route
  '/start/api-request': typeof demoStartApiRequestRoute
  '/tanstack-query/$id': typeof demoTanstackQueryIdRoute
  '/todos/$id': typeof demoTodosIdRoute
  '/todos2/$id': typeof demoTodos2IdRoute
  '/users/$id': typeof demoUsersIdRoute
  '/api/tq-todos/$id': typeof ApiTqTodosIdRoute
  '/test/$id/bonus': typeof TestIdBonusRoute
  '/await-with-catch/': typeof demoAwaitWithCatchIndexRoute
  '/server-pagination/': typeof demoServerPaginationIndexRoute
  '/suspense/': typeof demoSuspenseIndexRoute
  '/tanstack-query/': typeof demoTanstackQueryIndexRoute
  '/todos/': typeof demoTodosIndexRoute
  '/todos2/': typeof demoTodos2IndexRoute
  '/users/': typeof demoUsersIndexRoute
  '/api/tq-todos/': typeof ApiTqTodosIndexRoute
  '/test/nested/': typeof TestNestedIndexRoute
  '/catch-all/$id/$': typeof demoCatchAllIdSplatRoute
  '/start/ssr/data-only': typeof demoStartSsrDataOnlyRoute
  '/start/ssr/full-ssr': typeof demoStartSsrFullSsrRoute
  '/start/ssr/spa-mode': typeof demoStartSsrSpaModeRoute
  '/start/ssr/': typeof demoStartSsrIndexRoute
  '/tanstack-query/use-suspense-query/': typeof demoTanstackQueryUseSuspenseQueryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/test/$id': typeof TestIdRouteWithChildren
  '/test/no-layout': typeof TestNoLayoutRoute
  '/about': typeof AboutIndexRoute
  '/test': typeof TestIndexRoute
  '/api/names': typeof demoApiNamesRoute
  '/optional/{-$id}': typeof demoOptionalChar123IdChar125Route
  '/start/api-request': typeof demoStartApiRequestRoute
  '/tanstack-query/$id': typeof demoTanstackQueryIdRoute
  '/todos/$id': typeof demoTodosIdRoute
  '/todos2/$id': typeof demoTodos2IdRoute
  '/users/$id': typeof demoUsersIdRoute
  '/api/tq-todos/$id': typeof ApiTqTodosIdRoute
  '/test/$id/bonus': typeof TestIdBonusRoute
  '/await-with-catch': typeof demoAwaitWithCatchIndexRoute
  '/server-pagination': typeof demoServerPaginationIndexRoute
  '/suspense': typeof demoSuspenseIndexRoute
  '/tanstack-query': typeof demoTanstackQueryIndexRoute
  '/todos': typeof demoTodosIndexRoute
  '/todos2': typeof demoTodos2IndexRoute
  '/users': typeof demoUsersIndexRoute
  '/api/tq-todos': typeof ApiTqTodosIndexRoute
  '/test/nested': typeof TestNestedIndexRoute
  '/catch-all/$id/$': typeof demoCatchAllIdSplatRoute
  '/start/ssr/data-only': typeof demoStartSsrDataOnlyRoute
  '/start/ssr/full-ssr': typeof demoStartSsrFullSsrRoute
  '/start/ssr/spa-mode': typeof demoStartSsrSpaModeRoute
  '/start/ssr': typeof demoStartSsrIndexRoute
  '/tanstack-query/use-suspense-query': typeof demoTanstackQueryUseSuspenseQueryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/test': typeof TestRouteRouteWithChildren
  '/test/$id': typeof TestIdRouteWithChildren
  '/test_/no-layout': typeof TestNoLayoutRoute
  '/about/': typeof AboutIndexRoute
  '/test/': typeof TestIndexRoute
  '/(demo)/api/names': typeof demoApiNamesRoute
  '/(demo)/optional/{-$id}': typeof demoOptionalChar123IdChar125Route
  '/(demo)/start/api-request': typeof demoStartApiRequestRoute
  '/(demo)/tanstack-query/$id': typeof demoTanstackQueryIdRoute
  '/(demo)/todos/$id': typeof demoTodosIdRoute
  '/(demo)/todos2/$id': typeof demoTodos2IdRoute
  '/(demo)/users/$id': typeof demoUsersIdRoute
  '/api/tq-todos/$id': typeof ApiTqTodosIdRoute
  '/test/$id/bonus': typeof TestIdBonusRoute
  '/(demo)/await-with-catch/': typeof demoAwaitWithCatchIndexRoute
  '/(demo)/server-pagination/': typeof demoServerPaginationIndexRoute
  '/(demo)/suspense/': typeof demoSuspenseIndexRoute
  '/(demo)/tanstack-query/': typeof demoTanstackQueryIndexRoute
  '/(demo)/todos/': typeof demoTodosIndexRoute
  '/(demo)/todos2/': typeof demoTodos2IndexRoute
  '/(demo)/users/': typeof demoUsersIndexRoute
  '/api/tq-todos/': typeof ApiTqTodosIndexRoute
  '/test/nested/': typeof TestNestedIndexRoute
  '/(demo)/catch-all/$id/$': typeof demoCatchAllIdSplatRoute
  '/(demo)/start/ssr/data-only': typeof demoStartSsrDataOnlyRoute
  '/(demo)/start/ssr/full-ssr': typeof demoStartSsrFullSsrRoute
  '/(demo)/start/ssr/spa-mode': typeof demoStartSsrSpaModeRoute
  '/(demo)/start/ssr/': typeof demoStartSsrIndexRoute
  '/(demo)/tanstack-query/use-suspense-query/': typeof demoTanstackQueryUseSuspenseQueryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/test'
    | '/test/$id'
    | '/test/no-layout'
    | '/about/'
    | '/test/'
    | '/api/names'
    | '/optional/{-$id}'
    | '/start/api-request'
    | '/tanstack-query/$id'
    | '/todos/$id'
    | '/todos2/$id'
    | '/users/$id'
    | '/api/tq-todos/$id'
    | '/test/$id/bonus'
    | '/await-with-catch/'
    | '/server-pagination/'
    | '/suspense/'
    | '/tanstack-query/'
    | '/todos/'
    | '/todos2/'
    | '/users/'
    | '/api/tq-todos/'
    | '/test/nested/'
    | '/catch-all/$id/$'
    | '/start/ssr/data-only'
    | '/start/ssr/full-ssr'
    | '/start/ssr/spa-mode'
    | '/start/ssr/'
    | '/tanstack-query/use-suspense-query/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/test/$id'
    | '/test/no-layout'
    | '/about'
    | '/test'
    | '/api/names'
    | '/optional/{-$id}'
    | '/start/api-request'
    | '/tanstack-query/$id'
    | '/todos/$id'
    | '/todos2/$id'
    | '/users/$id'
    | '/api/tq-todos/$id'
    | '/test/$id/bonus'
    | '/await-with-catch'
    | '/server-pagination'
    | '/suspense'
    | '/tanstack-query'
    | '/todos'
    | '/todos2'
    | '/users'
    | '/api/tq-todos'
    | '/test/nested'
    | '/catch-all/$id/$'
    | '/start/ssr/data-only'
    | '/start/ssr/full-ssr'
    | '/start/ssr/spa-mode'
    | '/start/ssr'
    | '/tanstack-query/use-suspense-query'
  id:
    | '__root__'
    | '/'
    | '/test'
    | '/test/$id'
    | '/test_/no-layout'
    | '/about/'
    | '/test/'
    | '/(demo)/api/names'
    | '/(demo)/optional/{-$id}'
    | '/(demo)/start/api-request'
    | '/(demo)/tanstack-query/$id'
    | '/(demo)/todos/$id'
    | '/(demo)/todos2/$id'
    | '/(demo)/users/$id'
    | '/api/tq-todos/$id'
    | '/test/$id/bonus'
    | '/(demo)/await-with-catch/'
    | '/(demo)/server-pagination/'
    | '/(demo)/suspense/'
    | '/(demo)/tanstack-query/'
    | '/(demo)/todos/'
    | '/(demo)/todos2/'
    | '/(demo)/users/'
    | '/api/tq-todos/'
    | '/test/nested/'
    | '/(demo)/catch-all/$id/$'
    | '/(demo)/start/ssr/data-only'
    | '/(demo)/start/ssr/full-ssr'
    | '/(demo)/start/ssr/spa-mode'
    | '/(demo)/start/ssr/'
    | '/(demo)/tanstack-query/use-suspense-query/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TestRouteRoute: typeof TestRouteRouteWithChildren
  TestNoLayoutRoute: typeof TestNoLayoutRoute
  AboutIndexRoute: typeof AboutIndexRoute
  demoApiNamesRoute: typeof demoApiNamesRoute
  demoOptionalChar123IdChar125Route: typeof demoOptionalChar123IdChar125Route
  demoStartApiRequestRoute: typeof demoStartApiRequestRoute
  demoTanstackQueryIdRoute: typeof demoTanstackQueryIdRoute
  demoTodosIdRoute: typeof demoTodosIdRoute
  demoTodos2IdRoute: typeof demoTodos2IdRoute
  demoUsersIdRoute: typeof demoUsersIdRoute
  ApiTqTodosIdRoute: typeof ApiTqTodosIdRoute
  demoAwaitWithCatchIndexRoute: typeof demoAwaitWithCatchIndexRoute
  demoServerPaginationIndexRoute: typeof demoServerPaginationIndexRoute
  demoSuspenseIndexRoute: typeof demoSuspenseIndexRoute
  demoTanstackQueryIndexRoute: typeof demoTanstackQueryIndexRoute
  demoTodosIndexRoute: typeof demoTodosIndexRoute
  demoTodos2IndexRoute: typeof demoTodos2IndexRoute
  demoUsersIndexRoute: typeof demoUsersIndexRoute
  ApiTqTodosIndexRoute: typeof ApiTqTodosIndexRoute
  demoCatchAllIdSplatRoute: typeof demoCatchAllIdSplatRoute
  demoStartSsrDataOnlyRoute: typeof demoStartSsrDataOnlyRoute
  demoStartSsrFullSsrRoute: typeof demoStartSsrFullSsrRoute
  demoStartSsrSpaModeRoute: typeof demoStartSsrSpaModeRoute
  demoStartSsrIndexRoute: typeof demoStartSsrIndexRoute
  demoTanstackQueryUseSuspenseQueryIndexRoute: typeof demoTanstackQueryUseSuspenseQueryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/': {
      id: '/test/'
      path: '/'
      fullPath: '/test/'
      preLoaderRoute: typeof TestIndexRouteImport
      parentRoute: typeof TestRouteRoute
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test_/no-layout': {
      id: '/test_/no-layout'
      path: '/test/no-layout'
      fullPath: '/test/no-layout'
      preLoaderRoute: typeof TestNoLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/$id': {
      id: '/test/$id'
      path: '/$id'
      fullPath: '/test/$id'
      preLoaderRoute: typeof TestIdRouteImport
      parentRoute: typeof TestRouteRoute
    }
    '/test/nested/': {
      id: '/test/nested/'
      path: '/nested'
      fullPath: '/test/nested/'
      preLoaderRoute: typeof TestNestedIndexRouteImport
      parentRoute: typeof TestRouteRoute
    }
    '/api/tq-todos/': {
      id: '/api/tq-todos/'
      path: '/api/tq-todos'
      fullPath: '/api/tq-todos/'
      preLoaderRoute: typeof ApiTqTodosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(demo)/users/': {
      id: '/(demo)/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof demoUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(demo)/todos2/': {
      id: '/(demo)/todos2/'
      path: '/todos2'
      fullPath: '/todos2/'
      preLoaderRoute: typeof demoTodos2IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(demo)/todos/': {
      id: '/(demo)/todos/'
      path: '/todos'
      fullPath: '/todos/'
      preLoaderRoute: typeof demoTodosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(demo)/tanstack-query/': {
      id: '/(demo)/tanstack-query/'
      path: '/tanstack-query'
      fullPath: '/tanstack-query/'
      preLoaderRoute: typeof demoTanstackQueryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(demo)/suspense/': {
      id: '/(demo)/suspense/'
      path: '/suspense'
      fullPath: '/suspense/'
      preLoaderRoute: typeof demoSuspenseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(demo)/server-pagination/': {
      id: '/(demo)/server-pagination/'
      path: '/server-pagination'
      fullPath: '/server-pagination/'
      preLoaderRoute: typeof demoServerPaginationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(demo)/await-with-catch/': {
      id: '/(demo)/await-with-catch/'
      path: '/await-with-catch'
      fullPath: '/await-with-catch/'
      preLoaderRoute: typeof demoAwaitWithCatchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/$id/bonus': {
      id: '/test/$id/bonus'
      path: '/bonus'
      fullPath: '/test/$id/bonus'
      preLoaderRoute: typeof TestIdBonusRouteImport
      parentRoute: typeof TestIdRoute
    }
    '/api/tq-todos/$id': {
      id: '/api/tq-todos/$id'
      path: '/api/tq-todos/$id'
      fullPath: '/api/tq-todos/$id'
      preLoaderRoute: typeof ApiTqTodosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(demo)/users/$id': {
      id: '/(demo)/users/$id'
      path: '/users/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof demoUsersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(demo)/todos2/$id': {
      id: '/(demo)/todos2/$id'
      path: '/todos2/$id'
      fullPath: '/todos2/$id'
      preLoaderRoute: typeof demoTodos2IdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(demo)/todos/$id': {
      id: '/(demo)/todos/$id'
      path: '/todos/$id'
      fullPath: '/todos/$id'
      preLoaderRoute: typeof demoTodosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(demo)/tanstack-query/$id': {
      id: '/(demo)/tanstack-query/$id'
      path: '/tanstack-query/$id'
      fullPath: '/tanstack-query/$id'
      preLoaderRoute: typeof demoTanstackQueryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(demo)/start/api-request': {
      id: '/(demo)/start/api-request'
      path: '/start/api-request'
      fullPath: '/start/api-request'
      preLoaderRoute: typeof demoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(demo)/optional/{-$id}': {
      id: '/(demo)/optional/{-$id}'
      path: '/optional/{-$id}'
      fullPath: '/optional/{-$id}'
      preLoaderRoute: typeof demoOptionalChar123IdChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(demo)/api/names': {
      id: '/(demo)/api/names'
      path: '/api/names'
      fullPath: '/api/names'
      preLoaderRoute: typeof demoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(demo)/tanstack-query/use-suspense-query/': {
      id: '/(demo)/tanstack-query/use-suspense-query/'
      path: '/tanstack-query/use-suspense-query'
      fullPath: '/tanstack-query/use-suspense-query/'
      preLoaderRoute: typeof demoTanstackQueryUseSuspenseQueryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(demo)/start/ssr/': {
      id: '/(demo)/start/ssr/'
      path: '/start/ssr'
      fullPath: '/start/ssr/'
      preLoaderRoute: typeof demoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(demo)/start/ssr/spa-mode': {
      id: '/(demo)/start/ssr/spa-mode'
      path: '/start/ssr/spa-mode'
      fullPath: '/start/ssr/spa-mode'
      preLoaderRoute: typeof demoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(demo)/start/ssr/full-ssr': {
      id: '/(demo)/start/ssr/full-ssr'
      path: '/start/ssr/full-ssr'
      fullPath: '/start/ssr/full-ssr'
      preLoaderRoute: typeof demoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(demo)/start/ssr/data-only': {
      id: '/(demo)/start/ssr/data-only'
      path: '/start/ssr/data-only'
      fullPath: '/start/ssr/data-only'
      preLoaderRoute: typeof demoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(demo)/catch-all/$id/$': {
      id: '/(demo)/catch-all/$id/$'
      path: '/catch-all/$id/$'
      fullPath: '/catch-all/$id/$'
      preLoaderRoute: typeof demoCatchAllIdSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TestIdRouteChildren {
  TestIdBonusRoute: typeof TestIdBonusRoute
}

const TestIdRouteChildren: TestIdRouteChildren = {
  TestIdBonusRoute: TestIdBonusRoute,
}

const TestIdRouteWithChildren =
  TestIdRoute._addFileChildren(TestIdRouteChildren)

interface TestRouteRouteChildren {
  TestIdRoute: typeof TestIdRouteWithChildren
  TestIndexRoute: typeof TestIndexRoute
  TestNestedIndexRoute: typeof TestNestedIndexRoute
}

const TestRouteRouteChildren: TestRouteRouteChildren = {
  TestIdRoute: TestIdRouteWithChildren,
  TestIndexRoute: TestIndexRoute,
  TestNestedIndexRoute: TestNestedIndexRoute,
}

const TestRouteRouteWithChildren = TestRouteRoute._addFileChildren(
  TestRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TestRouteRoute: TestRouteRouteWithChildren,
  TestNoLayoutRoute: TestNoLayoutRoute,
  AboutIndexRoute: AboutIndexRoute,
  demoApiNamesRoute: demoApiNamesRoute,
  demoOptionalChar123IdChar125Route: demoOptionalChar123IdChar125Route,
  demoStartApiRequestRoute: demoStartApiRequestRoute,
  demoTanstackQueryIdRoute: demoTanstackQueryIdRoute,
  demoTodosIdRoute: demoTodosIdRoute,
  demoTodos2IdRoute: demoTodos2IdRoute,
  demoUsersIdRoute: demoUsersIdRoute,
  ApiTqTodosIdRoute: ApiTqTodosIdRoute,
  demoAwaitWithCatchIndexRoute: demoAwaitWithCatchIndexRoute,
  demoServerPaginationIndexRoute: demoServerPaginationIndexRoute,
  demoSuspenseIndexRoute: demoSuspenseIndexRoute,
  demoTanstackQueryIndexRoute: demoTanstackQueryIndexRoute,
  demoTodosIndexRoute: demoTodosIndexRoute,
  demoTodos2IndexRoute: demoTodos2IndexRoute,
  demoUsersIndexRoute: demoUsersIndexRoute,
  ApiTqTodosIndexRoute: ApiTqTodosIndexRoute,
  demoCatchAllIdSplatRoute: demoCatchAllIdSplatRoute,
  demoStartSsrDataOnlyRoute: demoStartSsrDataOnlyRoute,
  demoStartSsrFullSsrRoute: demoStartSsrFullSsrRoute,
  demoStartSsrSpaModeRoute: demoStartSsrSpaModeRoute,
  demoStartSsrIndexRoute: demoStartSsrIndexRoute,
  demoTanstackQueryUseSuspenseQueryIndexRoute:
    demoTanstackQueryUseSuspenseQueryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
